//
// Created by Mark Truluck on 1/9/21.
//

#ifndef FRAME_H
#define FRAME_H

#include <iostream>
#include <cstdlib>
#include <string>
#include <map>
#include <vector>

using namespace std;

/*
 * Class: Attr
 * ----------------------------
 *   Enables memory management of attribute data by
 *   being passed the type.  This is intended to be
 *   autogenerated per system by the Framepiler, 
 *   however can be maintained by hand.
 */

class Attr {
public:

    Attr(string name, string type, bool owned, void* pvAttr)
            : name(name), type(type), owned(owned), pvAttr(pvAttr) {}

    virtual ~Attr() {
        if (!owned) return;

        if (type == "int") delete (int*) pvAttr;
        else if (type == "string") delete(string*) pvAttr;
        else throw string("Trying to delete unknown attribute type.");
    }

public:

    string name;
    string type;
    bool owned;
    void* pvAttr;
};

/*
 * Class: FrameAttrs
 * ----------------------------
 *   Custom memory managed map for Frame 
 *   generated systems in C++.
 */

class FrameAttrs {
public:

    virtual ~FrameAttrs() {
        for (std::pair<std::string, Attr*> element : attribs) {
            delete element.second;
        }
    }

public:

    void add(string name, string type, bool owned, void* pvArg) {
        attribs.insert(std::pair<string,Attr*>(name,new Attr(name,type,owned,pvArg)));
    }

    void* get(string name) {
        std::map<string,Attr*>::iterator it;
        it = attribs.find(name);
        return it->second->pvAttr;
    }

    bool set(string name,void* pvNew) {
        std::map<string,Attr*>::iterator it;
        it = attribs.find(name);
        if (it == attribs.end()) {
            return false;
        }
        Attr* pAttr = it->second;
        assign(pAttr->type,it->second->pvAttr,pvNew);
        return true;
    }

    void assign(string type,void* pvTarget, void* pvSource) {
        if (type == "int") {
            *((int*) pvTarget) = *((int*) pvSource);
        } else if (type == "string") {
            *((string*) pvTarget) = *((string*) pvSource);
        }
    }

private:
    map<string, Attr*> attribs;
};


/*
 * Class: FrameEvent
 * ----------------------------
 *   FrameEvent is a core Frame type which is
 *   operated on by the Frame Language. Used 
 *   to implement Frame's reference architecture
 *   for state machine implementation. 
 */
 
class FrameEvent {

public:

    FrameEvent(string message, FrameAttrs* pParameters)
        : _message(message), _pParameters(pParameters) {
    }

    string _message;
    FrameAttrs* _pParameters;
    void* _pReturn;
};


/*
 * Class: StateContext
 * ----------------------------
 *   StateContext is an ancillary class 
 *   enabling proper operation of key features
 *   in Frame Notation. 
 */
 
class StateContext {

public:
    StateContext(FrameState state) : state(state), onStateStack(false) {
    }

    virtual ~StateContext() {
    };

    FrameAttrs* getStateArgs() {
        return &stateArgs;
    }

    void addStateArg(string name, string type, bool owned, void* pvArg) {
        stateArgs.add(name,type,owned,pvArg);
    }

    void* getStateArg(string name) {
        return stateArgs.get(name);
    }

    bool setStateArg(string name,void* pvNew) {
        return stateArgs.set(name, pvNew);
    }

    FrameAttrs* getStateVars() {
        return &stateVars;
    }

    void addStateVar(string name, string type, bool owned, void* pvArg) {
        stateVars.add(name,type,owned,pvArg);
    }

    void* getStateVar(string name) {
        stateVars.get(name);
    }

    bool setStateVar(string name,void* pvNew) {
        return stateVars.set(name,pvNew);
    }

    FrameAttrs* getEnterArgs() {
        return &enterArgs;
    }

    void addEnterArg(string name, string type, bool owned, void* pvArg) {
        enterArgs.add(name,type,owned,pvArg);
    }

    bool setEnterArg(string name,void* pvNew) {
        return enterArgs.set(name,pvNew);
    }

    void* getEnterArg(string name) {
        enterArgs.get(name);
    }


    void setOnStateStack(bool val) {
        onStateStack = val;
    }

    bool isOnStateStack() {
        return onStateStack;
    }

public:

    FrameState state;

private:
    bool onStateStack;

    FrameAttrs stateArgs;
    FrameAttrs stateVars;
    FrameAttrs enterArgs;

};

#endif //FRAME_H
